# -*- coding: utf-8 -*-
"""11-12-25_latest_agri_training_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uf8Qwck-e-N303bEuFqr_0I8O00UtSnq

Step 1: Install Dependencies
"""

!pip install -q transformers datasets peft librosa soundfile torch torchaudio accelerate bitsandbytes jiwer
!pip install -q huggingface_hub
!pip install -q torchcodec

import os
if 'google.colab' in str(get_ipython()):
    print("🔄 Restarting runtime...")
    os.kill(os.getpid(), 9)

# === Cell: Clear GPU Memory ===
import torch
import gc

# 1. Force Python's Garbage Collector to release unreferenced memory
gc.collect()

# 2. Clear PyTorch's internal CUDA cache
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect() # Optional: Clears shared memory if using multiprocessing

# 3. Print verification
print("✅ GPU Memory Cache Cleared")
if torch.cuda.is_available():
    print(f"Allocated: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
    print(f"Reserved:  {torch.cuda.memory_reserved() / 1024**3:.2f} GB")

"""Step 2: Configuration & Mount Drive"""

from google.colab import drive
import os
from huggingface_hub import login

print("🚀 Mounting Google Drive...")
drive.mount('/content/drive')

# --- CONFIGURATION ---
HF_TOKEN = "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" # <--- REPLACE WITH YOUR TOKEN
HF_DATASET_ID = "Be-win/malayalam-agri-speech"

# PATHS
# 1. Input: Your 50h General Malayalam Model
PREVIOUS_MODEL_PATH = "/content/drive/MyDrive/my_whisper_models/best_model"

# 2. Output: Where to save the FINAL Best Model
OUTPUT_DIR = "/content/drive/MyDrive/my_models/latest_agri_translation_model"

# 3. Checkpoints: Where to save resume files (intermediate states)
CHECKPOINT_DIR = "/content/drive/MyDrive/my_models/checkpoints_agri_translation"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# --- TRAINING SETTINGS ---
NUM_EPOCHS = 5
LEARNING_RATE = 3e-4
BATCH_SIZE = 32                 # Increased from 4 -> 32 (Huge speed boost)
GRADIENT_ACCUMULATION_STEPS = 1 # Reduced from 4 -> 1 (Updates weights faster)
PATIENCE = 2

login(token=HF_TOKEN)
print(f"✅ Configured for TRANSLATION.")
print(f"📂 Checkpoints will be saved to: {CHECKPOINT_DIR}")

"""Step 3: Load Existing Model & Merge (Critical Step)
This block is unique. It "bakes in" your previous training so the model treats your 50h Malayalam knowledge as its default state.
"""

import torch
from transformers import WhisperForConditionalGeneration, WhisperProcessor
from peft import PeftModel
import glob
import shutil

# 1. Setup Local Temp Dir
LOCAL_MODEL_DIR = "/content/temp_best_model"
if os.path.exists(LOCAL_MODEL_DIR):
    shutil.rmtree(LOCAL_MODEL_DIR)

# 2. Unzip 50h Model
zip_files = glob.glob(os.path.join(PREVIOUS_MODEL_PATH, "*.zip"))
if not zip_files:
    if os.path.exists(os.path.join(PREVIOUS_MODEL_PATH, "adapter_config.json")):
        model_path_to_use = PREVIOUS_MODEL_PATH
        print("📂 Found unzipped adapter.")
    else:
        raise FileNotFoundError(f"❌ No model found in {PREVIOUS_MODEL_PATH}")
else:
    latest_zip = max(zip_files, key=os.path.getctime)
    print(f"📦 Unzipping: {os.path.basename(latest_zip)}...")
    shutil.unpack_archive(latest_zip, LOCAL_MODEL_DIR)
    model_path_to_use = LOCAL_MODEL_DIR

# 3. Load & Merge
print("🤖 Loading Base Whisper...")
base_model = WhisperForConditionalGeneration.from_pretrained(
    "openai/whisper-medium", load_in_8bit=False, device_map="auto"
)

print("🔗 Merging 50h General Malayalam Adapter...")
model = PeftModel.from_pretrained(base_model, model_path_to_use)
model = model.merge_and_unload()

print("✅ Model Merged! Ready to learn Translation.")

"""Step 4: Load Dataset"""

from datasets import load_dataset, DatasetDict, Audio

print("📥 Loading Dataset...")
raw_dataset = load_dataset(HF_DATASET_ID, split="train", token=HF_TOKEN)

dataset_splits = raw_dataset.train_test_split(test_size=0.1)
common_voice = DatasetDict({
    "train": dataset_splits["train"],
    "test": dataset_splits["test"]
})

# --- KEY CHANGE: TASK = TRANSLATE ---
processor = WhisperProcessor.from_pretrained(
    "openai/whisper-medium",
    language="Malayalam",
    task="translate"
)
common_voice = common_voice.cast_column("audio", Audio(sampling_rate=16000))

def prepare_dataset(batch):
    audio = batch["audio"]
    batch["input_features"] = processor.feature_extractor(audio["array"], sampling_rate=16000).input_features[0]

    # --- KEY CHANGE: LABEL IS ENGLISH ---
    batch["labels"] = processor.tokenizer(batch["english_translation"]).input_ids
    return batch

print("⚙️ Preprocessing for Translation...")
common_voice = common_voice.map(prepare_dataset, remove_columns=common_voice.column_names["train"], num_proc=2)
print("✅ Dataset Ready (English targets).")

"""Cell 5: Apply New LoRA Adapter"""

from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from dataclasses import dataclass
from typing import Any, Dict, List, Union
import transformers

# 1. Silence Tokenizer Warnings
transformers.logging.set_verbosity_error()

# 2. Prepare Model for Training
model.gradient_checkpointing_enable()
model.config.use_cache = False

# --- CRITICAL FIX: ENABLE INPUT GRADS ---
# This ensures gradients flow through the frozen base model
if hasattr(model, "enable_input_require_grads"):
    model.enable_input_require_grads()
else:
    def make_inputs_require_grad(module, input, output):
        output.requires_grad_(True)
    model.get_input_embeddings().register_forward_hook(make_inputs_require_grad)

# 3. LoRA Config
config = LoraConfig(
    r=32,
    lora_alpha=64,
    # REMOVED "fc1", "fc2" to keep memory usage safe
    target_modules=["q_proj", "v_proj", "k_proj", "out_proj"],
    lora_dropout=0.05,
    bias="none"
)

model = get_peft_model(model, config)
model.print_trainable_parameters()

# 4. Data Collator
@dataclass
class DataCollatorSpeechSeq2SeqWithPadding:
    processor: Any
    def __call__(self, features):
        input_features = [{"input_features": feature["input_features"]} for feature in features]
        batch = self.processor.feature_extractor.pad(input_features, return_tensors="pt")
        label_features = [{"input_ids": feature["labels"]} for feature in features]
        labels_batch = self.processor.tokenizer.pad(label_features, return_tensors="pt")
        labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)
        if (labels[:, 0] == self.processor.tokenizer.bos_token_id).all().cpu().item():
            labels = labels[:, 1:]
        batch["labels"] = labels
        return batch

data_collator = DataCollatorSpeechSeq2SeqWithPadding(processor=processor)

"""Cell 6: Manual Training Loop (With Early Stopping)"""

import torch
from torch.utils.data import DataLoader
from tqdm.auto import tqdm
import gc
import glob

# --- 1. SETUP ---
torch.cuda.empty_cache()
gc.collect()

train_dataloader = DataLoader(
    common_voice["train"],
    shuffle=True,
    batch_size=BATCH_SIZE,
    collate_fn=data_collator,
    num_workers=8,  # Increased from 2 -> 8 (Feeds GPU faster)
    pin_memory=True
)

eval_dataloader = DataLoader(
    common_voice["test"],
    batch_size=BATCH_SIZE,
    collate_fn=data_collator,
    num_workers=8,  # Increased from 2 -> 8
    pin_memory=True
)

optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)

# --- 2. RESUME LOGIC ---
start_epoch = 0
best_val_loss = float('inf')
early_stopping_counter = 0

# Check for existing checkpoints
checkpoints = glob.glob(os.path.join(CHECKPOINT_DIR, "checkpoint_epoch_*.pt"))
if checkpoints:
    latest_checkpoint = max(checkpoints, key=os.path.getctime)
    print(f"🔄 Found checkpoint: {latest_checkpoint}")
    print("   Resuming training...")

    checkpoint_data = torch.load(latest_checkpoint)
    model.load_state_dict(checkpoint_data['model_state_dict'])
    optimizer.load_state_dict(checkpoint_data['optimizer_state_dict'])
    start_epoch = checkpoint_data['epoch'] + 1
    best_val_loss = checkpoint_data.get('best_val_loss', float('inf'))
    early_stopping_counter = checkpoint_data.get('early_stopping_counter', 0)

    print(f"   ⏩ Resuming from Epoch {start_epoch+1}")
else:
    print("✨ No checkpoint found. Starting fresh.")

# --- 3. TRAINING LOOP ---
print("🔥 Starting Translation Training...")
model.train()

for epoch in range(start_epoch, NUM_EPOCHS):
    print(f"\n=== Epoch {epoch + 1}/{NUM_EPOCHS} ===")

    # TRAIN
    model.train()
    total_train_loss = 0
    progress_bar = tqdm(train_dataloader, desc="Training")

    for step, batch in enumerate(progress_bar):
        batch = {k: v.to("cuda") for k, v in batch.items()}
        outputs = model(**batch)
        loss = outputs.loss / GRADIENT_ACCUMULATION_STEPS
        loss.backward()

        if (step + 1) % GRADIENT_ACCUMULATION_STEPS == 0:
            optimizer.step()
            optimizer.zero_grad()

        current_loss = loss.item() * GRADIENT_ACCUMULATION_STEPS
        total_train_loss += current_loss
        progress_bar.set_postfix({"loss": f"{current_loss:.4f}"})

    avg_train_loss = total_train_loss / len(train_dataloader)
    print(f"📉 Avg Train Loss: {avg_train_loss:.4f}")

    # VALIDATE
    print("🔎 Validating...")
    model.eval()
    total_val_loss = 0
    torch.cuda.empty_cache()

    with torch.no_grad():
        for batch in tqdm(eval_dataloader, desc="Validating"):
            batch = {k: v.to("cuda") for k, v in batch.items()}
            outputs = model(**batch)
            total_val_loss += outputs.loss.item()

    avg_val_loss = total_val_loss / len(eval_dataloader)
    print(f"📊 Validation Loss: {avg_val_loss:.4f}")

    # SAVE CHECKPOINT (For Resuming)
    ckpt_path = os.path.join(CHECKPOINT_DIR, f"checkpoint_epoch_{epoch}.pt")
    torch.save({
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'best_val_loss': best_val_loss,
        'early_stopping_counter': early_stopping_counter
    }, ckpt_path)
    print(f"💾 Checkpoint saved: {ckpt_path}")

    # CLEANUP OLD CHECKPOINTS (Keep last 2)
    all_ckpts = sorted(glob.glob(os.path.join(CHECKPOINT_DIR, "checkpoint_epoch_*.pt")), key=os.path.getctime)
    if len(all_ckpts) > 2:
        os.remove(all_ckpts[0]) # Remove oldest

    # CHECK BEST MODEL
    if avg_val_loss < best_val_loss:
        print(f"🏆 Best Loss! ({best_val_loss:.4f} -> {avg_val_loss:.4f}). Saving final model...")
        best_val_loss = avg_val_loss
        early_stopping_counter = 0

        # Save Hugging Face style model
        model.save_pretrained(OUTPUT_DIR)
        processor.save_pretrained(OUTPUT_DIR)
    else:
        early_stopping_counter += 1
        print(f"⚠️ No improvement. Patience: {early_stopping_counter}/{PATIENCE}")
        if early_stopping_counter >= PATIENCE:
            print("🛑 Early stopping triggered!")
            break

print("\n✅ Training Finished.")